apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payments.fullname" . }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.config.keycloakIssuerUri | quote }}
  OTLP_TRACING_ENDPOINT: {{ .Values.config.otlpTracingEndpoint | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername | quote }}
  FINCORE_PAYMENTS_BANK_SANDBOX_ENABLED: {{ .Values.config.sandboxBankEnabled | quote }}
  FINCORE_PAYMENTS_DISPATCHER_ENABLED: {{ .Values.config.dispatcherEnabled | quote }}
  FINCORE_PAYMENTS_RETRY_ENABLED: {{ .Values.config.retryEnabled | quote }}
  FINCORE_EVENTBUS_BOOTSTRAP_SERVERS: {{ .Values.config.eventbusBootstrapServers | quote }}
